export const ROLES = Object.freeze({
  PLAYER: 'PLAYER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  MONEY_ADMIN: 'MONEY_ADMIN',
});

export const USER_VERIFICATION_STATUSES = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

export const ROUND_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  UPCOMING: 'UPCOMING',
  OPEN: 'OPEN',
  FILLING: 'FILLING',
  FULL: 'FULL',
  READY: 'READY',
  DRAWING: 'DRAWING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const PAYMENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
});

export const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_VERIFICATION_APPROVED: 'USER_VERIFICATION_APPROVED',
  USER_VERIFICATION_REJECTED: 'USER_VERIFICATION_REJECTED',
  ROUND_CREATED: 'ROUND_CREATED',
  ROUND_UPDATED: 'ROUND_UPDATED',
  ENTRY_LOCKED: 'ENTRY_LOCKED',
  PAYMENT_RECEIPT_UPLOADED: 'PAYMENT_RECEIPT_UPLOADED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  ROUND_DRAW_REQUESTED: 'ROUND_DRAW_REQUESTED',
  ROUND_WINNERS_SELECTED: 'ROUND_WINNERS_SELECTED',
  ROUND_COMPLETED: 'ROUND_COMPLETED',
  ROUND_STATUS_CHANGED: 'ROUND_STATUS_CHANGED',
  WALLET_DEPOSIT_CREATED: 'WALLET_DEPOSIT_CREATED',
  WALLET_DEPOSIT_COMPLETED: 'WALLET_DEPOSIT_COMPLETED',
  WALLET_DEPOSIT_REJECTED: 'WALLET_DEPOSIT_REJECTED',
  WALLET_WITHDRAWAL_CREATED: 'WALLET_WITHDRAWAL_CREATED',
  WALLET_WITHDRAWAL_APPROVED: 'WALLET_WITHDRAWAL_APPROVED',
  WALLET_WITHDRAWAL_REJECTED: 'WALLET_WITHDRAWAL_REJECTED',
  PRIZE_PAYMENT_CREDITED: 'PRIZE_PAYMENT_CREDITED',
  LIVE_BROADCAST_CREATED: 'LIVE_BROADCAST_CREATED',
  LIVE_BROADCAST_STARTED: 'LIVE_BROADCAST_STARTED',
  LIVE_BROADCAST_STOPPED: 'LIVE_BROADCAST_STOPPED',
  FINANCIAL_SETTINGS_UPDATED: 'FINANCIAL_SETTINGS_UPDATED',
  PAYMENT_METHOD_CREATED: 'PAYMENT_METHOD_CREATED',
  PAYMENT_METHOD_UPDATED: 'PAYMENT_METHOD_UPDATED',
  PAYMENT_METHOD_DELETED: 'PAYMENT_METHOD_DELETED',
  PAYMENT_METHOD_TOGGLED: 'PAYMENT_METHOD_TOGGLED',
});

export const TRANSACTION_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
});

export const TRANSACTION_TYPES = Object.freeze({
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
});

export const BROADCAST_STATUSES = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  LIVE: 'LIVE',
  STOPPED: 'STOPPED',
  ERROR: 'ERROR',
});
