export const ROLES = Object.freeze({
  PLAYER: 'PLAYER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  MONEY_ADMIN: 'MONEY_ADMIN',
  GAME_ADMIN: 'GAME_ADMIN',
});

export const USER_VERIFICATION_STATUSES = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

export const ROUND_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  UPCOMING: 'UPCOMING',
  OPEN: 'OPEN',
  FILLING: 'FILLING',
  FULL: 'FULL',
  READY: 'READY',
  DRAWING: 'DRAWING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const PAYMENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
});

export const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_VERIFICATION_APPROVED: 'USER_VERIFICATION_APPROVED',
  USER_VERIFICATION_REJECTED: 'USER_VERIFICATION_REJECTED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_DELETED: 'ADMIN_DELETED',
  ADMIN_ROLE_CHANGED: 'ADMIN_ROLE_CHANGED',
  ADMIN_PERMISSION_CHANGED: 'ADMIN_PERMISSION_CHANGED',
  ROUND_CREATED: 'ROUND_CREATED',
  ROUND_UPDATED: 'ROUND_UPDATED',
  ENTRY_LOCKED: 'ENTRY_LOCKED',
  PAYMENT_RECEIPT_UPLOADED: 'PAYMENT_RECEIPT_UPLOADED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  ROUND_DRAW_REQUESTED: 'ROUND_DRAW_REQUESTED',
  ROUND_WINNERS_SELECTED: 'ROUND_WINNERS_SELECTED',
  ROUND_COMPLETED: 'ROUND_COMPLETED',
  ROUND_STATUS_CHANGED: 'ROUND_STATUS_CHANGED',
  WALLET_DEPOSIT_CREATED: 'WALLET_DEPOSIT_CREATED',
  WALLET_DEPOSIT_COMPLETED: 'WALLET_DEPOSIT_COMPLETED',
  WALLET_DEPOSIT_REJECTED: 'WALLET_DEPOSIT_REJECTED',
  WALLET_WITHDRAWAL_CREATED: 'WALLET_WITHDRAWAL_CREATED',
  WALLET_WITHDRAWAL_APPROVED: 'WALLET_WITHDRAWAL_APPROVED',
  WALLET_WITHDRAWAL_REJECTED: 'WALLET_WITHDRAWAL_REJECTED',
  WALLET_WITHDRAWAL_READY_FOR_PAYMENT: 'WALLET_WITHDRAWAL_READY_FOR_PAYMENT',
  WALLET_WITHDRAWAL_PROCESSING: 'WALLET_WITHDRAWAL_PROCESSING',
  WALLET_WITHDRAWAL_PAID: 'WALLET_WITHDRAWAL_PAID',
  WALLET_WITHDRAWAL_CANCELLED: 'WALLET_WITHDRAWAL_CANCELLED',
  PRIZE_PAYMENT_CREDITED: 'PRIZE_PAYMENT_CREDITED',
  LIVE_BROADCAST_CREATED: 'LIVE_BROADCAST_CREATED',
  LIVE_BROADCAST_STARTED: 'LIVE_BROADCAST_STARTED',
  LIVE_BROADCAST_STOPPED: 'LIVE_BROADCAST_STOPPED',
  FINANCIAL_SETTINGS_UPDATED: 'FINANCIAL_SETTINGS_UPDATED',
  PLATFORM_FEE_CHANGED: 'PLATFORM_FEE_CHANGED',
  GAME_PRICE_CHANGED: 'GAME_PRICE_CHANGED',
  GOVERNMENT_PAYMENT_CHANGED: 'GOVERNMENT_PAYMENT_CHANGED',
  APPROVAL_THRESHOLD_CHANGED: 'APPROVAL_THRESHOLD_CHANGED',
  PAYMENT_METHOD_CREATED: 'PAYMENT_METHOD_CREATED',
  PAYMENT_METHOD_UPDATED: 'PAYMENT_METHOD_UPDATED',
  PAYMENT_METHOD_DELETED: 'PAYMENT_METHOD_DELETED',
  PAYMENT_METHOD_ACTIVATED: 'PAYMENT_METHOD_ACTIVATED',
  PAYMENT_METHOD_DEACTIVATED: 'PAYMENT_METHOD_DEACTIVATED',
  WITHDRAWAL_TRANSFER_PROOF_UPLOADED: 'WITHDRAWAL_TRANSFER_PROOF_UPLOADED',
});

export const NOTIFICATION_TYPES = Object.freeze({
  NEW_DEPOSIT: 'NEW_DEPOSIT',
  NEW_WITHDRAWAL: 'NEW_WITHDRAWAL',
  NEW_USER_VERIFICATION: 'NEW_USER_VERIFICATION',
  DEPOSIT_RECEIPT_SUBMITTED: 'DEPOSIT_RECEIPT_SUBMITTED',
  WITHDRAWAL_REQUEST: 'WITHDRAWAL_REQUEST',
  GAME_EVENT: 'GAME_EVENT',
});

export const TRANSACTION_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  READY_FOR_PAYMENT: 'READY_FOR_PAYMENT',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

export const TRANSACTION_TYPES = Object.freeze({
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
});

export const BROADCAST_STATUSES = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  LIVE: 'LIVE',
  STOPPED: 'STOPPED',
  ERROR: 'ERROR',
});
